# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: basics-books
author: basics
logo: logo.svg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
parse:
  myst_enable_extensions:
    - dollarmath
    - amsmath
    - colon_fence
    - deflist
    - html_admonition
    - html_image
    - linkify
    - substitution
    - tasklist
    - smartquotes

execute:
  execute_notebooks: auto
  
# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/Basics2022/bbooks  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

# sphinx extensions
sphinx:
  config:
    language: en
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js
    - https://cdn.jsdelivr.net/npm/loading-attribute-polyfill@2.1.0/dist/loading-attribute-polyfill.min.js
    suppress_warnings: ["mystnb.unknown_mime_type"]
#   mystnb_render_text_attachments: true
#   mystnb_output_mime_priority:
#     - application/vnd.plotly.v1+json
#     - text/html
#     - text/markdown
#     - image/svg+xml
#     - image/png
#     - image/jpeg
#     - text/plain_
    html_show_copyright: false
    html_theme_options:
      logo:
        image_light: logo.svg
        image_dark: logo-dark.svg
      repository_url: https://github.com/Basics2022/bbooks-physics-hs  # Online location of your book
      repository_branch: master
      use_repository_button: True
      use_edit_page_button: True
      use_issues_button: True
      launch_buttons:
        colab_url: "https://colab.research.google.com"    # colab
      collapse_navigation: False
#     navigation_depth: 2
      search_bar_position: sidebar
    html_favicon: favicon-sugar.svg
  extra_extensions:
    - sphinx_proof
    - sphinx_exercise
    # - sphinx_togglebutton   # to be installed


